### ISSUE TITLE
RFC: Change packaging

### ISSUE THREAD

**Issue by scohen** [pinterest/elixir-thrift#144]
Assume we have a service called `Pinterest.UserService`. 

Presently, we generate:
  * `Pinterest.UserService.Server.Framed`
  * `Pinterest.UserService.Client.Framed`
  * `Pinterst.UserService.Server.Handler.Behaviour`

I suggest moving them to 
  * `Pinterest.UserService.Handler`
  * `Pinterest.UserService.Binary.Framed.Server`
  * `Pinterest.UserService.Binary.Framed.Client`

Similarly, I'll place the server / client implementations in 
  * `Thrift.Impl.Binary.Framed.Client`
  * `Thrift.Impl.Binary.Framed.Server`

This will make aliases nicer, we can `alias Pinterest.UserService.Binary.Framed.Server` and reference it as `Server` rather than `Framed`. 

@dantswain @pguillory @jparise Thoughts?

**Comment by jparise** [comment]
I like the `Pinterest.UserService.Handler` change; let's move forward with that.

Because this is all generated code, would it be too limiting to just generate `Pinterest.UserService.{Client,Server}` directly? They would be "binary framed" by default because that's all we support today, but perhaps the code generator could be informed which variant should be used for each generated schema. That would be the simplest output, but again it might be too limiting.

I'm also not a big fan of the `Impl` name in your last list. Could we drop that?

**Comment by scohen** [comment]
Ok, everyone likes the handler change; so that stays.

I think generating `Pinterest.UserService.{Client, Server}` would indeed be too limiting, because we're almost certainly going to embark on TMux and Finagle versions shortly. I'd rather not dig out of that hole. 

We can drop Impl. I wasn't super happy with that.

**Comment by jparise** [comment]
Cool, so we can definitely rule out that approach. Everything else looks reasonable to me. Let's adopt your suggestions and get a feel for it in practice.

**Comment by scohen** [comment]
Ok, I'll put out a PR.

**Comment by pguillory** [comment]
I would be more in favor of putting everything in a single level under the user-defined name. Given the correspondence between module name and file name, this results in a simpler directory structure.

{namespace}.{name}.BinaryFramedClient
{namespace}.{name}.BinaryFramedServer
{namespace}.{name}.Handler

What's the benefit of the extra dots?

**Comment by scohen** [comment]
It makes the dependencies clear. 
Imagine when we have Framed / TMux / Finagle transports and Binary / Compact / JSON protocols

Also, the alias works better `Server` rather than `BinaryFramedServer`
