### ISSUE TITLE
Thrift compiler being run on test files

### ISSUE THREAD

**Issue by pguillory** [pinterest/elixir-thrift#181]
When I try to run a specific test in my project by name, the compile.thrift gets invoked on the test file. The first line of my test output is then a parse error, where it's trying to parse the Elixir source code as Thrift.
```bash
$ mix test test/whatever.exs
Failed to parse test/whatever_test.exs: Error parsing thrift file test/whatever_test.exs on line 6: {:illegal, '@'}
<test continues to run...>
```
I tried modifying the run method to raise an error
```bash
~/code/plex (master)  $ mix test test/whatever_test.exs
==> thrift
Compiling 1 file (.ex)
** (RuntimeError) boom, args = ["test/whatever_test.exs"]
    lib/mix/tasks/compile.thrift.ex:38: Mix.Tasks.Compile.Thrift.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/compile.all.ex:19: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:37: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.ex:85: Mix.Tasks.Compile.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
```

**Comment by jparise** [comment]
I think this is an argument parsing problem. I shouldn't be assuming all arguments that are visible to the compiler task are meant for it.

I think a reasonable fix might be only inspecting the argument list when we know we've been invoked as a standalone mix task. I'll try to make that work.

**Comment by jparise** [comment]
There doesn't appear to be a way for a Mxi task to determine how it was invoked. That's unfortunate because there is some future functionality that I would like to make conditional on that, too.

I think the best solution is to go back to having two discrete Mix tasks:

1. `compile.thrift`, which integrates specifically with the `Mix.Project` and compiler toolchain
2. `thrift.generate`, which is tailored for interactive command line usage

**Comment by jparise** [comment]
@pguillory, did #186 fix this problem for you?

**Comment by pguillory** [comment]
Yes thanks Jon.
