### ISSUE TITLE
Question: Any support or workaround for interceptors (middleware) in the server?

### ISSUE THREAD

**Issue by bjuretic** [pinterest/elixir-thrift#325]
Hello,

is there a way to add interceptors / middleware / filters - like functions to the server? The usual stuff like logging, tracing, authorization, etc but implemented outside of the actual functions called by the server.

For example:

```
defmodule Auth.UserServer do
  @behaviour Auth.UserService.Handler

  intercept Auth.MyLogger, some: :opts
  intercept Auth.MyTracer

  ... actual server methods
end
```

So this is basically a `plug` model; interceptor takes some context, request and response and calls the next interceptor, until it reaches the actual server method in the end, and then it goes through the same process for the response.

**Comment by fishcakez** [comment]
There isn't any built in support for these features. However since a behavior is defined for the generated modules it is possible to implement this outside of elixir-thrift. The callbacks can be discovered for meta-programming by calling `behaviour_info/1`, e.g. `Auth.UserService.Handler.behaviour_info(:callbacks)`.
